### PR TITLE
Feature: Mochawesome parser

### PR DESCRIPTION
**Pull request by jmuleiro**
## Context
I recently started using this tool to integrate `mochawesome` reports with Slack. It turns out, in my test cases I have feature flags that cause Cypress tests to be skipped. Mochawesome has two types of skipped tests: `skipped` and `pending`. But as it turns out, `mocha` does not. This caused the parser to interpret tests marked as `skipped` by Mochawesome as failures, and to list them as such.

I updated the `mocha` parser so that it deals with this issue if it finds `skipped` keys in test results/suites.

## Changes
- Updated `mocha` parser
  - If the raw JSON has a `skipped` property, it adds those tests to the list of tests marked with a pending state
- Added `mochawesome` test case for results with skipped, non-pending tests
- Renamed test file `skipped-tests` to `pending-tests` to match its behavior (and updated test description)
- Updated GitHub Actions `node-version` to latest
- Fixed `ReferenceError` when result type is set to unsupported parser

## Sample file
Here's a sample JSON test result with which you can reproduce the unintended behavior:
[flipcard-submit.json](https://github.com/test-results-reporter/parser/files/15266743/flipcard-submit.json)

### CODE REVIEW

**Comment by ASaiAnudeep** [comment]
hey @jmuleiro ,

- can we just update the existing mocha file to support your scenario.
- please add a new test to check the combination of skipped and pending scenarios.

**Comment by jmuleiro** [comment]
@ASaiAnudeep @leelaprasadv done!

**Comment by ASaiAnudeep** [comment]
@jmuleiro do you mind updating the node versions to latest in **build** yaml file.
- build: `node-version: [18.x, 20.x]`

**Comment by jmuleiro** [comment]
@ASaiAnudeep done, also took the liberty of fixing a small `ReferenceError` that occurred when the parser type was set to an unsupported parser.

**Review by ASaiAnudeep — APPROVED** [review]

**Comment by ASaiAnudeep** [comment]
@jmuleiro thanks a lot for your contributions. The new version [v0.1.15](https://github.com/test-results-reporter/parser/releases/tag/v0.1.15) has been released.

Please use the latest version of testbeats to see your changes.
```sh
npx testbeats@latest publish -c path/to/config.json
```

**Pull request merged**
